# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: codeexec.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'codeexec.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63odeexec.proto\"(\n\nTwoNumbers\x12\x0c\n\x04num1\x18\x01 \x01(\x02\x12\x0c\n\x04num2\x18\x02 \x01(\x02\"\x1a\n\nNumberList\x12\x0c\n\x04nums\x18\x01 \x03(\x02\"\x1a\n\nListResult\x12\x0c\n\x04nums\x18\x01 \x03(\x02\"\x15\n\x04Text\x12\r\n\x05value\x18\x01 \x01(\t\"\x17\n\x06Result\x12\r\n\x05value\x18\x01 \x01(\x02\x32y\n\x08\x43odeExec\x12\x1b\n\x03\x41\x64\x64\x12\x0b.TwoNumbers\x1a\x07.Result\x12 \n\x04Sort\x12\x0b.NumberList\x1a\x0b.ListResult\x12\x15\n\x05Upper\x12\x05.Text\x1a\x05.Text\x12\x17\n\x07Reverse\x12\x05.Text\x1a\x05.Textb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'codeexec_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TWONUMBERS']._serialized_start=18
  _globals['_TWONUMBERS']._serialized_end=58
  _globals['_NUMBERLIST']._serialized_start=60
  _globals['_NUMBERLIST']._serialized_end=86
  _globals['_LISTRESULT']._serialized_start=88
  _globals['_LISTRESULT']._serialized_end=114
  _globals['_TEXT']._serialized_start=116
  _globals['_TEXT']._serialized_end=137
  _globals['_RESULT']._serialized_start=139
  _globals['_RESULT']._serialized_end=162
  _globals['_CODEEXEC']._serialized_start=164
  _globals['_CODEEXEC']._serialized_end=285
# @@protoc_insertion_point(module_scope)
